print('--Hello! Here you can calculate the area of a room in m^2.--')
width = float(input('Type the width in meter--> '))
lenght = float(input('Type the lenght in meter--> '))
area = (width * lenght)
print('The area of the room is-->',area,'m^2')